[package]
name = "telemetry"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
dotenvy = "0.15"
db = { path = "../db" }
redis = { version = "0.27", features = ["tokio-comp", "streams"] }
serde_json = "1.0.149"
sqlx = { workspace = true }
tokio = { version = "1.50.0", features = ["full"] }
tracing = "0.1.44"
uuid = { version = "1.21.0", features = ["v4"] }
anyhow = "1.0.102"

[lints]
workspace = true
