use std::fs;
use std::path::Path;

use common::error::OxideError;

use crate::detect::Language;

/// Nixpkgs' well-known placeholder hash — building against it always fails,
/// and the failure message contains the real expected hash. Used for Go
/// (vendorHash) and npm (npmDepsHash) builds, neither of which Nix can
/// compute without either vendoring deps itself or a prior build attempt.
const FAKE_HASH: &str = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";

pub struct GeneratedFlake {
    /// True for Go/JS/TS: the flake was written with FAKE_HASH and needs a
    /// throwaway build attempt to discover the real hash before it'll work.
    pub needs_hash_retry: bool,
}

pub fn generate(repo_dir: &Path, lang: Language) -> Result<GeneratedFlake, OxideError> {
    let (content, needs_hash_retry) = match lang {
        Language::Rust => (rust_flake(repo_dir)?, false),
        Language::Go => (go_flake(repo_dir)?, true),
        Language::TypeScript => (node_flake(repo_dir, true)?, true),
        Language::JavaScript => (node_flake(repo_dir, false)?, true),
        Language::Python => (python_flake(repo_dir)?, false),
    };
    fs::write(repo_dir.join("flake.nix"), content)
        .map_err(|e| OxideError::Build(format!("failed to write generated flake.nix: {e}")))?;
    Ok(GeneratedFlake { needs_hash_retry })
}

/// Patches FAKE_HASH out for the real hash Nix reported. Called between the
/// throwaway first build attempt and the real one, for languages where
/// `GeneratedFlake::needs_hash_retry` is true.
pub fn patch_hash(repo_dir: &Path, real_hash: &str) -> Result<(), OxideError> {
    let flake_path = repo_dir.join("flake.nix");
    let content = fs::read_to_string(&flake_path)
        .map_err(|e| OxideError::Build(format!("failed to read flake.nix for hash patch: {e}")))?;
    fs::write(&flake_path, content.replace(FAKE_HASH, real_hash))
        .map_err(|e| OxideError::Build(format!("failed to write patched flake.nix: {e}")))
}

/// Pulls the real hash out of a Nix fixed-output-derivation mismatch error,
/// e.g. a line like `       got:    sha256-AbCd...=`.
pub fn extract_real_hash(nix_stderr: &str) -> Option<String> {
    nix_stderr.lines().find_map(|line| {
        line.trim()
            .strip_prefix("got:")
            .map(|rest| rest.trim().to_string())
    })
}

fn rust_flake(repo_dir: &Path) -> Result<String, OxideError> {
    let cargo_toml_str = fs::read_to_string(repo_dir.join("Cargo.toml"))
        .map_err(|e| OxideError::Build(format!("failed to read Cargo.toml: {e}")))?;
    let cargo_toml: toml::Value = cargo_toml_str
        .parse()
        .map_err(|e| OxideError::Build(format!("failed to parse Cargo.toml: {e}")))?;

    let pkg_name = cargo_toml
        .get("package")
        .and_then(|p| p.get("name"))
        .and_then(|n| n.as_str())
        .ok_or_else(|| OxideError::Build("Cargo.toml is missing [package].name".to_string()))?;

    // If [[bin]] isn't specified, cargo's default binary name is the
    // package name.
    let bin_name = cargo_toml
        .get("bin")
        .and_then(|b| b.as_array())
        .and_then(|arr| arr.first())
        .and_then(|b| b.get("name"))
        .and_then(|n| n.as_str())
        .unwrap_or(pkg_name);

    Ok(format!(
        r#"{{
  description = "Auto-generated by Oxide for a Rust app ({pkg_name})";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  outputs = {{ self, nixpkgs }}:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs {{ inherit system; }};
      app = pkgs.pkgsStatic.rustPlatform.buildRustPackage {{
        pname = "{pkg_name}";
        version = "0.1.0";
        src = ./.;
        cargoLock.lockFile = ./Cargo.lock;
      }};
    in {{
      packages.${{system}}.default = pkgs.runCommand "oxide-image-context" {{}} ''
        mkdir -p $out/bin
        cp ${{app}}/bin/{bin_name} $out/bin/{bin_name}
        cat > $out/Dockerfile <<'DOCKERFILE_EOF'
FROM scratch
COPY bin/{bin_name} /app
EXPOSE 3000
ENTRYPOINT ["/app"]
DOCKERFILE_EOF
      '';
    }};
}}
"#
    ))
}

fn go_flake(repo_dir: &Path) -> Result<String, OxideError> {
    let go_mod = fs::read_to_string(repo_dir.join("go.mod"))
        .map_err(|e| OxideError::Build(format!("failed to read go.mod: {e}")))?;
    let module_path = go_mod
        .lines()
        .find_map(|l| l.trim().strip_prefix("module ").map(str::trim))
        .ok_or_else(|| OxideError::Build("go.mod is missing a module directive".to_string()))?;
    let bin_name = module_path.rsplit('/').next().unwrap_or("app");

    Ok(format!(
        r#"{{
  description = "Auto-generated by Oxide for a Go app ({module_path})";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  outputs = {{ self, nixpkgs }}:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs {{ inherit system; }};
      app = pkgs.buildGoModule {{
        pname = "{bin_name}";
        version = "0.1.0";
        src = ./.;
        vendorHash = "{FAKE_HASH}";
        CGO_ENABLED = 0;
      }};
    in {{
      packages.${{system}}.default = pkgs.runCommand "oxide-image-context" {{}} ''
        mkdir -p $out/bin
        cp ${{app}}/bin/{bin_name} $out/bin/{bin_name}
        cat > $out/Dockerfile <<'DOCKERFILE_EOF'
FROM scratch
COPY bin/{bin_name} /app
EXPOSE 3000
ENTRYPOINT ["/app"]
DOCKERFILE_EOF
      '';
    }};
}}
"#
    ))
}

fn node_flake(repo_dir: &Path, is_typescript: bool) -> Result<String, OxideError> {
    let package_json_str = fs::read_to_string(repo_dir.join("package.json"))
        .map_err(|e| OxideError::Build(format!("failed to read package.json: {e}")))?;
    let package_json: serde_json::Value = serde_json::from_str(&package_json_str)
        .map_err(|e| OxideError::Build(format!("failed to parse package.json: {e}")))?;

    let name = package_json
        .get("name")
        .and_then(|n| n.as_str())
        .unwrap_or("oxide-app");
    let main = package_json.get("main").and_then(|m| m.as_str());
    let default_entry = if is_typescript {
        "dist/index.js"
    } else {
        "index.js"
    };
    let entry = main.unwrap_or(default_entry);
    // TypeScript needs `npm run build` to produce the entry file;
    // JavaScript runs directly, no build step.
    let dont_npm_build = !is_typescript;

    Ok(format!(
        r#"{{
  description = "Auto-generated by Oxide for a Node app ({name})";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  outputs = {{ self, nixpkgs }}:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs {{ inherit system; }};
      app = pkgs.buildNpmPackage {{
        pname = "{name}";
        version = "0.1.0";
        src = ./.;
        npmDepsHash = "{FAKE_HASH}";
        dontNpmBuild = {dont_npm_build};
        installPhase = ''
          mkdir -p $out
          cp -r . $out/app
        '';
      }};
    in {{
      packages.${{system}}.default = pkgs.runCommand "oxide-image-context" {{}} ''
        mkdir -p $out
        cp -r ${{app}}/app $out/app
        cat > $out/Dockerfile <<DOCKERFILE_EOF
FROM node:22-slim
COPY app /app
WORKDIR /app
EXPOSE 3000
ENTRYPOINT ["node", "{entry}"]
DOCKERFILE_EOF
      '';
    }};
}}
"#
    ))
}

fn python_flake(repo_dir: &Path) -> Result<String, OxideError> {
    let entry = ["main.py", "app.py"]
        .into_iter()
        .find(|f| repo_dir.join(f).is_file())
        .ok_or_else(|| {
            OxideError::Build(
                "Python auto-detection needs a main.py or app.py entrypoint at the repo root"
                    .to_string(),
            )
        })?;

    // pyproject.toml-only repos (poetry/pdm/etc.) aren't supported by this
    // pip-based generator yet — requires requirements.txt.
    if !repo_dir.join("requirements.txt").is_file() {
        return Err(OxideError::Build(
            "Python auto-detection currently requires a requirements.txt (pyproject.toml-only repos aren't supported yet)"
                .to_string(),
        ));
    }

    Ok(format!(
        r#"{{
  # NOTE: unlike the other generated flakes, this one is NOT fully
  # reproducible — `pip install` runs with network access during the build
  # (impure) because there's no solid nixpkgs-native way to hermetically
  # vendor arbitrary requirements.txt the way buildGoModule/buildNpmPackage
  # do for their ecosystems. See benchmarks.md / README for the tradeoff.
  description = "Auto-generated by Oxide for a Python app (impure pip install)";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  outputs = {{ self, nixpkgs }}:
    let
      system = "x86_64-linux";
      pkgs = import nixpkgs {{ inherit system; }};
    in {{
      packages.${{system}}.default = pkgs.stdenv.mkDerivation {{
        pname = "oxide-app";
        version = "0.1.0";
        src = ./.;
        buildInputs = [ pkgs.python3 pkgs.python3Packages.pip ];
        dontBuild = true;
        installPhase = ''
          mkdir -p $out/app
          cp -r . $out/app
          ${{pkgs.python3}}/bin/python3 -m pip install --no-cache-dir --target $out/app/deps -r requirements.txt
          cat > $out/Dockerfile <<DOCKERFILE_EOF
FROM python:3.12-slim
COPY app /app
WORKDIR /app
ENV PYTHONPATH=/app/deps
EXPOSE 3000
ENTRYPOINT ["python3", "{entry}"]
DOCKERFILE_EOF
        '';
      }};
    }};
}}
"#
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn scratch_dir(name: &str) -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(format!("oxide-flakegen-test-{}", name));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn rust_flake_uses_bin_name_when_specified() {
        let dir = scratch_dir("rust-bin");
        fs::write(
            dir.join("Cargo.toml"),
            r#"[package]
name = "my-crate"

[[bin]]
name = "my-server"
path = "src/main.rs"
"#,
        )
        .unwrap();
        let content = rust_flake(&dir).unwrap();
        assert!(content.contains(r#"pname = "my-crate""#));
        assert!(content.contains("bin/my-server"));
    }

    #[test]
    fn rust_flake_falls_back_to_package_name_without_bin_section() {
        let dir = scratch_dir("rust-nobin");
        fs::write(dir.join("Cargo.toml"), "[package]\nname = \"solo\"\n").unwrap();
        let content = rust_flake(&dir).unwrap();
        assert!(content.contains("bin/solo"));
    }

    #[test]
    fn go_flake_derives_binary_name_from_module_path() {
        let dir = scratch_dir("go");
        fs::write(
            dir.join("go.mod"),
            "module github.com/acme/widget\n\ngo 1.22\n",
        )
        .unwrap();
        let content = go_flake(&dir).unwrap();
        assert!(content.contains("bin/widget"));
        assert!(content.contains(FAKE_HASH));
    }

    #[test]
    fn typescript_flake_runs_build_and_uses_dist_entry() {
        let dir = scratch_dir("ts");
        fs::write(dir.join("package.json"), r#"{"name":"api"}"#).unwrap();
        let content = node_flake(&dir, true).unwrap();
        assert!(content.contains("dontNpmBuild = false"));
        assert!(content.contains(r#"ENTRYPOINT ["node", "dist/index.js"]"#));
    }

    #[test]
    fn javascript_flake_skips_build_and_uses_index_entry() {
        let dir = scratch_dir("js");
        fs::write(dir.join("package.json"), r#"{"name":"api"}"#).unwrap();
        let content = node_flake(&dir, false).unwrap();
        assert!(content.contains("dontNpmBuild = true"));
        assert!(content.contains(r#"ENTRYPOINT ["node", "index.js"]"#));
    }

    #[test]
    fn python_flake_requires_an_entrypoint_file() {
        let dir = scratch_dir("py-noentry");
        fs::write(dir.join("requirements.txt"), "flask\n").unwrap();
        assert!(python_flake(&dir).is_err());
    }

    #[test]
    fn python_flake_requires_requirements_txt() {
        let dir = scratch_dir("py-noreqs");
        fs::write(dir.join("main.py"), "print('hi')\n").unwrap();
        assert!(python_flake(&dir).is_err());
    }

    #[test]
    fn python_flake_succeeds_with_entry_and_requirements() {
        let dir = scratch_dir("py-ok");
        fs::write(dir.join("main.py"), "print('hi')\n").unwrap();
        fs::write(dir.join("requirements.txt"), "flask\n").unwrap();
        let content = python_flake(&dir).unwrap();
        assert!(content.contains(r#"ENTRYPOINT ["python3", "main.py"]"#));
    }

    #[test]
    fn extract_real_hash_parses_nix_mismatch_output() {
        let stderr = "error: hash mismatch\n  specified: sha256-AAAA=\n       got:    sha256-RealHashValue123=\n";
        assert_eq!(
            extract_real_hash(stderr),
            Some("sha256-RealHashValue123=".to_string())
        );
    }

    #[test]
    fn extract_real_hash_returns_none_for_unrelated_errors() {
        assert_eq!(extract_real_hash("error: something else entirely"), None);
    }

    #[test]
    fn patch_hash_replaces_placeholder_in_written_flake() {
        let dir = scratch_dir("patch");
        fs::write(dir.join("go.mod"), "module example.com/svc\n").unwrap();
        generate(&dir, Language::Go).unwrap();
        patch_hash(&dir, "sha256-TheRealHash=").unwrap();
        let content = fs::read_to_string(dir.join("flake.nix")).unwrap();
        assert!(content.contains("sha256-TheRealHash="));
        assert!(!content.contains(FAKE_HASH));
    }
}
